[37.567853928] 2018-01-14 17:22:57,313 - INFO - launcher: Starting sanity checks
[37.567853928] 2018-01-14 17:22:57,313 - INFO - launcher: Checking for Python 3.5+
[38.566350937] 2018-01-14 17:22:57,314 - INFO - launcher: Checking console encoding
[38.566350937] 2018-01-14 17:22:57,314 - INFO - launcher: Setting console encoding to UTF-8
[38.566350937] 2018-01-14 17:22:57,314 - INFO - launcher: Ensuring we're in the right environment
[39.568662643] 2018-01-14 17:22:57,315 - INFO - launcher: Adding local bins/ folder to path
[40.568113327] 2018-01-14 17:22:57,316 - INFO - launcher: Required checks passed.
[41.569948196] 2018-01-14 17:22:57,317 - INFO - launcher: Optional checks passed.
[42.567253113] 2018-01-14 17:22:57,318 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.7118594646453857] 2018-01-14 17:22:58,988 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 213 in _setup_logging: Set logging level to INFO
[1.7128591537475586] 2018-01-14 17:22:58,989 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 80 in __init__: =========== MusicBot (version 1.9.6_1) ===========
[1.7128591537475586] 2018-01-14 17:22:58,989 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 86 in __init__: Loaded autoplaylist with 2531 entries
[1.714859486] launcher-INFO: Connecting
[4.1368889808654785] 2018-01-14 17:23:01,413 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 1011 in on_ready: Connection established, ready to go.
[4.1368889808654785] 2018-01-14 17:23:01,413 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 324 in _cache_app_info: Caching app info
[4.2316272258758545] 2018-01-14 17:23:01,507 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 828 in _scheck_ensure_env: Ensuring data folders exist
[4.2326006889343262] 2018-01-14 17:23:01,508 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 844 in _scheck_server_permissions: Checking server permissions
[4.2326006889343262] 2018-01-14 17:23:01,508 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 848 in _scheck_autoplaylist: Auditing autoplaylist
[4.2326006889343262] 2018-01-14 17:23:01,508 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 852 in _scheck_configs: Validating config
[4.2326006889343262] 2018-01-14 17:23:01,508 - DEBUG - musicbot.config | In config.py::MainThread(13024), line 155 in async_validate: Validating options...
[4.2326006889343262] 2018-01-14 17:23:01,508 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 855 in _scheck_configs: Validating permissions config
[4.2326006889343262] 2018-01-14 17:23:01,508 - DEBUG - musicbot.permissions | In permissions.py::MainThread(13024), line 59 in async_validate: Validating permissions...
[4.2336003780364990] 2018-01-14 17:23:01,509 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1022 in on_ready: Connected to Discord!
[4.2336003780364990] 2018-01-14 17:23:01,509 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1032 in on_ready: Bot:   402211201565851668/Music-bot#9903 [BOT]
[4.2346019744873047] 2018-01-14 17:23:01,510 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1040 in on_ready: Owner: 285441389083492352/exwingzero#5672

[4.2346019744873047] 2018-01-14 17:23:01,510 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1043 in on_ready: Server List:
[4.2346019744873047] 2018-01-14 17:23:01,510 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1044 in <listcomp>:  - mer
[4.2356009483337402] 2018-01-14 17:23:01,511 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1088 in on_ready: Not bound to any text channels
[4.2356009483337402] 2018-01-14 17:23:01,511 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1114 in on_ready: Not autojoining any voice channels
[4.2356009483337402] 2018-01-14 17:23:01,511 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1118 in on_ready: Options:
[4.2366006374359131] 2018-01-14 17:23:01,512 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1120 in on_ready:   Command prefix: !
[4.2366006374359131] 2018-01-14 17:23:01,512 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1121 in on_ready:   Default volume: 25%
[4.2376019954681396] 2018-01-14 17:23:01,513 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1123 in on_ready:   Skip threshold: 4 votes or 50%
[4.2376019954681396] 2018-01-14 17:23:01,513 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1124 in on_ready:   Now Playing @mentions: Disabled
[4.2376019954681396] 2018-01-14 17:23:01,513 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1125 in on_ready:   Auto-Summon: Enabled
[4.2376019954681396] 2018-01-14 17:23:01,513 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1126 in on_ready:   Auto-Playlist: Enabled
[4.2386023998260498] 2018-01-14 17:23:01,514 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1127 in on_ready:   Auto-Pause: Enabled
[4.2396025657653809] 2018-01-14 17:23:01,515 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1128 in on_ready:   Delete Messages: Enabled
[4.2406013011932373] 2018-01-14 17:23:01,516 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1130 in on_ready:     Delete Invoking: Disabled
[4.2406013011932373] 2018-01-14 17:23:01,516 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1131 in on_ready:   Debug Mode: Disabled
[4.2416033744812012] 2018-01-14 17:23:01,517 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 1132 in on_ready:   Downloaded songs will be saved
[4.2446007728576660] 2018-01-14 17:23:01,520 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 258 in _join_startup_channels: Found owner in "#chillmusic"
[4.2456030845642090] 2018-01-14 17:23:01,521 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 267 in _join_startup_channels: Attempting to join mer/#chillmusic
[4.2466013431549072] 2018-01-14 17:23:01,522 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 437 in get_voice_client: Connection attempt 1 to #chillmusic
[4.2476012706756592] 2018-01-14 17:23:01,523 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(13024), line 376 in join_voice_channel: (join_voice_channel) creating futures
[4.2476012706756592] 2018-01-14 17:23:01,523 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(13024), line 382 in join_voice_channel: (join_voice_channel) setting voice state
[4.2476012706756592] 2018-01-14 17:23:01,523 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(13024), line 385 in join_voice_channel: (join_voice_channel) waiting for session id
[4.3881008625030518] 2018-01-14 17:23:01,664 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(13024), line 2564 in on_voice_state_update: Voice state update for 402211201565851668/Music-bot#9903 on mer/#chillmusic -> [JOIN, CONNECT]
[4.3886198997497559] 2018-01-14 17:23:01,664 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 2575 in on_voice_state_update: 402211201565851668/Music-bot#9903 has joined mer/#chillmusic
[4.3896000385284424] 2018-01-14 17:23:01,665 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(13024), line 389 in join_voice_channel: (join_voice_channel) waiting for voice data
[4.3900995254516602] 2018-01-14 17:23:01,666 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(13024), line 403 in join_voice_channel: (join_voice_channel) connecting...
[4.5424568653106689] 2018-01-14 17:23:01,818 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(13024), line 415 in join_voice_channel: (join_voice_channel) connection successful
[4.5429449081420898] 2018-01-14 17:23:01,819 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 463 in get_voice_client: Connected in 0.3s
[4.5429449081420898] 2018-01-14 17:23:01,819 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 464 in get_voice_client: Connected to mer/#chillmusic
[4.5439436435699463] 2018-01-14 17:23:01,820 - INFO - musicbot.bot | In bot.py::MainThread(13024), line 283 in _join_startup_channels: Joined mer/#chillmusic
[4.5594663619995117] 2018-01-14 17:23:01,835 - VOICEDEBUG - musicbot.player | In player.py::MainThread(13024), line 311 in websocket_check: Starting websocket check loop for mer
[7.7278385162353516] 2018-01-14 17:23:05,003 - INFO - musicbot.entry | In entry.py::MainThread(13024), line 219 in _really_download: Download started: https://youtube.com/watch?v=uqzQfOKZoPc
[9.2907841205596924] 2018-01-14 17:23:06,566 - INFO - musicbot.entry | In entry.py::MainThread(13024), line 226 in _really_download: Download complete: https://youtube.com/watch?v=uqzQfOKZoPc
[9.7334773540496826] 2018-01-14 17:23:07,009 - FFMPEG - musicbot.player | In player.py::MainThread(13024), line 268 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-uqzQfOKZoPc-Zeds_Dead_x_Diplo_ft_Elliphant_-_Blame.webm
[10.0560743808746338] 2018-01-14 17:23:07,332 - DEBUG - musicbot.bot | In bot.py::MainThread(13024), line 781 in serialize_queue: Serializing queue for 402208071134216193
